apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dbgate
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nvd11/my-shared-helm-charts.git'
    path: charts/generic-web-service
    targetRevision: 'v1.1.3'
    helm:
      values: |
        replicaCount: 1
        containerPort: 3000

        nodeSelector:
          kubernetes.io/hostname: nuc

        image:
          repository: dbgate/dbgate
          tag: latest
          pullPolicy: IfNotPresent

        env:
          - name: WEB_ROOT
            value: /dbgate

        livenessProbe:
          path: /dbgate/
          initialDelaySeconds: 15
          periodSeconds: 20

        readinessProbe:
          path: /dbgate/
          initialDelaySeconds: 15
          periodSeconds: 20

        service:
          type: ClusterIP
          port: 80

        route:
          enabled: true
          parentGateway: kong-main-gateway
          path: /dbgate
  destination:
    name: 'tencent-dp1-cluster'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/parentRefs/0/group
        - /spec/parentRefs/0/kind
        - /status
