apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gemini-live-bridge
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nvd11/my-shared-helm-charts.git'
    path: charts/generic-web-service
    targetRevision: 'v1.1.3'
    
    helm:
      values: |
        replicaCount: 1
        containerPort: 8080
        
        nodeSelector:
          kubernetes.io/arch: "arm64"
          kubernetes.io/hostname: "free-arm-vm"

        envFrom:
          - configMapRef:
              name: gemini-live-bridge-config
          - secretRef:
              name: gemini-live-bridge-secrets

        image:
          repository: ghcr.io/nvd11/gemini-live-bridge
          tag: sha-48caaa09bfef095e716ef5209fac5447b52f73a7
          pullPolicy: IfNotPresent
          
        livenessProbe:
          path: /q/health/live
          initialDelaySeconds: 15
          periodSeconds: 20
          
        readinessProbe:
          path: /q/health/ready
          initialDelaySeconds: 10
          periodSeconds: 15
          
        service:
          type: ClusterIP
          port: 80
          targetPort: 8080
  destination:
    name: 'tencent-dp1-cluster'
    namespace: gemini-bridge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
