apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-ingress-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # 🎯 同步波次 2：等 CRD 字典安装好后，再安装控制器
spec:
  project: default
  source:
    repoURL: 'https://charts.konghq.com'
    chart: kong
    targetRevision: 2.38.0
    helm:
      values: |
        ingressController:
          installCRDs: false # 因为我们已经在波次 1 独立安装了，所以这里设为 false
        env:
          database: "off"
          # 目标 3: 监听 TCP 6379 (Kong stream 模式)
          nginx_stream_listen: "[::]:6379"
        gateway:
          # 开启 Kong 的 Gateway API 监听能力
          enabled: true
        deployment:
          # DaemonSet 模式: 每个节点 1 个 controller pod, 无需硬编码副本数
          daemonset: true
        proxy:
          # 目标 2: 设置外部流量策略为 Local, 避免跨节点路由, 就近访问本节点的 Controller Pod
          externalTrafficPolicy: Local
          # 目标 3: 开启 TCP stream 转发能力 (透传 TCP, 供 Redis/MySQL 等使用)
          stream:
            - containerPort: 6379
              servicePort: 6379
  destination:
    name: 'tencent-dp1-cluster'
    namespace: kong-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
