apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-svc
  namespace: argocd # 🎯 部署在 ArgoCD 控制面所在的命名空间，由其进行调度
spec:
  project: default
  source:
    repoURL: 'https://github.com/nvd11/my-shared-helm-charts.git' # 🎯 跨仓库引用我们的公共 Helm 模板仓库！
    path: charts/generic-web-service # 🎯 引用通用的 Web 服务子文件夹
    targetRevision: 'v1.1.3' # 🎯 使用新增了 nodeSelector 支持的 v1.1.3 模具！
    
    # 🎯 🌟 极简参数注入：完全告别冗长的 K8s 物理 YAML 编写！
    helm:
      values: |
        replicaCount: 1
        containerPort: 8080 # Quarkus 默认容器端口
        
        nodeSelector:
          kubernetes.io/hostname: "nuc" # 🎯 锁定调度到 NUC 节点
        
        image:
          repository: ghcr.io/nvd11/my-quarkus-svc
          tag: 2fc15c18670d0dab2b1f89f67b4db28b39b25726 # 🎯 自动与您的 GitHub Actions CI 产出的镜像 tag 保持对齐
          pullPolicy: IfNotPresent
          
        livenessProbe:
          path: /svc1 # 临时以我们刚才写好的 API 路径作为健康指标
          initialDelaySeconds: 15
          periodSeconds: 20
          
        readinessProbe:
          path: /svc1
          initialDelaySeconds: 15
          periodSeconds: 20
          
        service:
          type: ClusterIP
          port: 80
          
        route:
          enabled: true
          parentGateway: kong-main-gateway # 🎯 认领基础设施大门
          path: /svc1
  destination:
    name: 'tencent-dp1-cluster' # 🎯 极客解耦：使用在 ArgoCD 中注册的集群别名，彻底避免在 Git 图纸中硬编码公网 IP 和端口！
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
