apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sms-flink-lakehouse
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4" # 🎯 业务批处理层
spec:
  project: default
  source:
    repoURL: 'https://github.com/nvd11/my-argocd-manifests.git'
    path: infrastructure/sms-flink-lakehouse
    targetRevision: HEAD
  destination:
    name: 'tencent-dp1-cluster'
    namespace: finance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
